name        = Template
description = A template project for a common usage
version     = 1.0.0

url         = https://github.com/Akazukin-Team/Template-Repository

vendor      = Akazukin-Team
vendor-url  = https://github.com/Akazukin-Team
