name: Add review label


on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  issues:
    types: [opened, reopened, labeled, unlabeled]
  issue_comment:
    types: [created, edited]


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  add-unchecked-label:
    if: (github.event_name == 'issues' || github.event_name == 'pull_request') && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')

    runs-on: ubuntu-22.04

    steps:
      - name: Add 'review/unchecked' label
        run: |
          gh ${{ github.event_name == 'issues' && 'issue edit ${{ github.event.issue.number }}' || 'pr edit ${{ github.event.pull_request.number }}' }} --add-label 'review/unchecked'
          exit 0

  add-checked-label:
    if: github.event_name == 'issue_comment'

    runs-on: ubuntu-22.04

    steps:
      - name: Add 'review/checked' label
        run: |
          gh ${{ github.event.issue.pull_request && 'pr' || 'issue' }} edit ${{ github.event.pull_request.number }} --add-label 'review/checked'
          exit 0


  fix-label:
    if: (github.event_name == 'issues' || github.event_name == 'pull_request') && (github.event.action == 'labeled' || github.event.action == 'unlabeled')

    runs-on: ubuntu-22.04

    steps:
      # Add label
      - name: Remove 'review/checked' label from issue
        if: github.event.action == 'labeled' && github.event.label.name == 'review/unchecked'
        run: |
          gh ${{ github.event_name == 'issues' && 'issue edit ${{ github.event.issue.number }}' || 'pr edit ${{ github.event.pull_request.number }}' }} --remove-label 'review/checked'
          exit 0

      - name: Remove 'review/unchecked' label from issue
        if: github.event.action == 'labeled' && github.event.label.name == 'review/checked'
        run: |
          gh ${{ github.event_name == 'issues' && 'issue edit ${{ github.event.issue.number }}' || 'pr edit ${{ github.event.pull_request.number }}' }} --remove-label 'review/unchecked'
          exit 0

      # Remove label
      - name: Remove 'review/checked' label from issue
        if: github.event.action == 'unlabeled' && github.event.label.name == 'review/unchecked'
        run: |
          gh ${{ github.event_name == 'issues' && 'issue edit ${{ github.event.issue.number }}' || 'pr edit ${{ github.event.pull_request.number }}' }} --add-label 'review/checked'
          exit 0

      - name: Remove 'review/unchecked' label from issue
        if: github.event.action == 'unlabeled' && github.event.label.name == 'review/checked'
        run: |
          gh ${{ github.event_name == 'issues' && 'issue edit ${{ github.event.issue.number }}' || 'pr edit ${{ github.event.pull_request.number }}' }} --add-label 'review/unchecked'
          exit 0
